### PR TITLE
887862: Automation missed files changes removed 

### PR DESCRIPTION
**Pull request by ghost**
### Description 

The app.modules file is removed from the code snippet and the respective files changes for that removed files also update in this pr https://github.com/syncfusion-content/ej2-pdfviewer-angular-docs/pull/194/files but due to the automation failure the files changes for the app.modules.ts is not removed in the custom-context-menu.md file so made that changes manually in this PR.

### CODE REVIEW

**Review by johnsonmonohar — APPROVED** [review]
Approved

**Comment by johnsonmonohar** [comment]
@Syncfusion-CI  - Please merge this PR to resolve the failure.

**Comment by johnsonmonohar** [comment]
rebuild

**Comment by Edberg-Vasan** [comment]
rebuild

**Pull request merged**
